apiVersion: apps/v1
kind: Deployment
metadata:
  name: gulimall-member
  namespace: gulimall
  labels:
    app: gulimall-member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gulimall-member
  template:
    metadata:
      labels:
        app: gulimall-member
    spec:
      containers:
        - name: gulimall-member
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 500m
              memory: 500Mi
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: gulimall-member
  namespace: gulimall
  labels:
    app: gulimall-member
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32003
      protocol: TCP
  selector:
    app: gulimall-member
  type: NodePort