server:
  port: 8080
spring:
  cloud:

  application:
    name: gulimall-third-party
  zipkin:
    base-url: http://zipkin.gulimall:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
    nacos:
      discovery:
        server-addr: nacos.gulimall:8848
    sentinel:
      transport:
        port: 8719
        dashboard: sentinel.gulimall:8080
    alicloud:
      sms:
        access-key-id: LTAI4G454cBvWSbPFH4HEVHi
        access-secret: agDTsCPziuMMBbolQlucIa5cCkKlEn
        sys-domain: dysmsapi.aliyuncs.com
        sys-version: "2017-05-25"
        region-id: cn-hangzhou
        sign-name: 豪大大博客
        template-code: SMS_205434954
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket-name: gulimall-hgg
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.sleuth: debug
    org.springframework.cloud.openfeign: debug

