spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-cart
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.10
  session:
    store-type: redis
server:
  port: 19000
gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10
    capacity: 100000